version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: symfony-php
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/application
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: symfony-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: symfony-phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
    depends_on:
      - database

volumes:
  db-data:
